### ISSUE TITLE
UI spectactularly fails on listing documents

### ISSUE THREAD

**Issue by basilesimon** [digitalevidencetoolkit/deptoolkit#67]
When calling `/api/list-docs` as far as I can tell. Seems to be happening on the new laptop. Config below:

```
$ npm --version
8.1.0

$ node --version
v16.13.0
```

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///Users/b/github/deptoolkit/deptoolkit/ui/node_modules/@sveltejs/kit/dist/install-fetch.js:1244:16)
    at file:///Users/b/github/deptoolkit/deptoolkit/ui/node_modules/@sveltejs/kit/dist/install-fetch.js:1453:19
    at new Promise (<anonymous>)
    at fetch (file:///Users/b/github/deptoolkit/deptoolkit/ui/node_modules/@sveltejs/kit/dist/install-fetch.js:1451:9)
    at Module.fetchData (/src/lib/Ledger/index.ts:9:21)
    at eval (/Users/b/github/deptoolkit/deptoolkit/ui/src/routes/library.svelte:25:61)
    at Object.$$render (/Users/b/github/deptoolkit/deptoolkit/ui/node_modules/svelte/internal/index.js:1677:22) {
  input: '/api/list-docs',
  code: 'ERR_INVALID_URL'
}
```

**Comment by basilesimon** [comment]
A tentative package upgrade led to [the introduction of breaking changes](https://github.com/sveltejs/kit/pull/3384)
